# Install dependencies for AI4FluidSimulations

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
  
    name: Julia ${{ matrix.version }} - ${{ matrix.tests }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      test_suite:  ${{ matrix.tests }}

    strategy:
      fail-fast: false

      matrix:
        version: ['1.6', '1.7']
        os: [ubuntu-latest]

    steps:
      - name: Checkout AI4FluidSimulations.jl
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python depdendencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install torch zarr h5py numpy azure-storage-blob azure-batch==9.0.0 azure-storage-queue==1.4.0 cupy-cuda115
          
      - name: Install Julia depdendencies
        run: |
          julia -e 'using Pkg; Pkg.add(["PyCall", "WaterLily", "AzureClusterlessHPC", "JLD", "HDF5", "PyPlot"])'
          
      - name: Build AI4FluidSimulations.jl
        uses: julia-actions/julia-buildpkg@latest

      - name: Rebuild PyCall with system python
        run: |
          export PYTHON=$(which python)
          julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.build("PyCall")'
      - name: Run tests
        run: |
          julia test/runtests.jl